data:
    dataset: MPI3D
    filepath: /pfs/work9/workspace/scratch/ma_iadam-mcbm/datasets/mpi3d/mpi3d_real.npz
    task: object_shape
    concepts: [object_color, object_size, camera_height, background_color]
    nuisances_task: [horizontal_axis]

model:
    model_type: mcbm
    encoder:
        arch: resnet20
    hidden_dims_y: 64
    var_z: 1
    hidden_dims_c: [3]
    beta: 1
    hidden_dims_z: null
    gamma: 1

training:
    batch_size: 128
    n_epochs: 50
    save_epochs: 5
    optimizer:    
        optimizer: SGD
        base_batch_size: 64
        base_lr: 0.003
        batch_size: 128
        momentum: 0.9
        weight_decay: 0.00004
    scheduler:
        gamma: 0.1
        scheduler: StepLR
        step_size: 20
